//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_abbreviations_english
    {
        public int id { get; set; }
        public string a { get; set; }
        public int b { get; set; }
        public bool p { get; set; }
    }
}
