//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bible_version_key
    {
        public int id { get; set; }
        public string table { get; set; }
        public string abbreviation { get; set; }
        public string language { get; set; }
        public string version { get; set; }
        public string info_text { get; set; }
        public string info_url { get; set; }
        public string publisher { get; set; }
        public string copyright { get; set; }
        public string copyright_info { get; set; }
    }
}
